export const UI_DEBUG_TOGGLE = "EXPLORER/UI/DEBUG/TOGGLE";
export const UI_QUERY_OPTIONS_TOGGLE = "EXPLORER/UI/QUERYPANEL/OPTIONS/TOGGLE";
export const UI_SERVER_INFO = "EXPLORER/UI/SERVER_INFO";
export const UI_STARRED_TOGGLE = "EXPLORER/UI/STARRED/TOGGLE";
export const UI_TABS_SELECT = "EXPLORER/UI/TABS/SELECT";
export const UI_THEME_TOGGLE = "EXPLORER/UI/THEME/TOGGLE";
