export const EventType = {
  BooleanToggle: "boolean_toggle",
  CubeSelect: "cube_select",
  CubeSubtopic: "cube_subtopic",
  CubeTable: "cube_table",
  CubeTopic: "cube_topic",
  CutAdd: "cut_add",
  CutMembers: "cut_members",
  CutReload: "cut_reload",
  CutRemove: "cut_remove",
  CutToggle: "cut_toggle",
  CutsClear: "cuts_clear",
  Download: "download",
  DrilldownAdd: "drilldown_add",
  DrilldownCaption: "drilldown_caption",
  DrilldownProperties: "drilldown_properties",
  DrilldownRemove: "drilldown_remove",
  DrilldownToggle: "drilldown_toggle",
  DrilldownsClear: "drilldowns_clear",
  ExecuteQuery: "execute_query",
  LocaleChange: "locale_change",
  MeasureSearch: "measure_search",
  MeasureToggle: "measure_toggle",
  MeasuresClear: "measures_clear",
  PaginationLimit: "pagination_limit",
  PaginationOffset: "pagination_offset",
  PreviewToggle: "preview_toggle",
  SortDirection: "sort_direction",
  SortMeasure: "sort_measure",
  TabSwitch: "tab_switch",
} as const;

export type EventType = (typeof EventType)[keyof typeof EventType];
